name: Build Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.1.1'

      - name: Build
        run: gradle build
        working-directory: leapmod

      - uses: actions/upload-artifact@v4
        with:
          name: leapmod-jar
          path: leapmod/build/libs/*.jar
